// The WebGL shader is generated from the Metal source, never written beside it.
//
// Two hand-maintained copies of the same two hundred lines of noise is one copy that goes
// wrong where nobody is looking — and the one that goes wrong is always the one nobody is
// developing in. Only *mechanical* differences belong here: types, address-space
// qualifiers, integer literal suffixes, and how a fragment returns. Every surface equation
// lives in the Metal file and arrives here untouched.
//
//   node scripts/generate-shader.mjs           rewrite src/shaders.ts
//   node scripts/generate-shader.mjs --check   fail if it is out of date
import { readFileSync, writeFileSync } from 'node:fs'

const metalURL = new URL('../../Sources/MoonletPlanet/Shaders/PlanetRenderer.metal', import.meta.url)
const source = readFileSync(metalURL, 'utf8')

const fields = source.match(/typedef struct \{([\s\S]*?)\} MoonletPlanetUniforms;/)?.[1]
if (!fields) throw new Error('Planet uniform structure missing')

const functionsStart = source.indexOf('float moonletHash')
const fragmentStart = source.indexOf('fragment half4 moonletPlanetFragment')
if (functionsStart < 0 || fragmentStart < 0) throw new Error('Planet shader structure missing')
const functions = source.slice(functionsStart, fragmentStart)
const fragment = source.slice(source.indexOf('{', fragmentStart) + 1, source.lastIndexOf('}'))

const translate = value => value
  // Address spaces and reference parameters. GLSL has neither, but it has `out`.
  .replaceAll('constant MoonletPlanetUniforms &u', 'MoonletPlanetUniforms u')
  .replace(/thread\s+(\w+)\s*&\s*(\w+)/g, 'out $1 $2')
  // Types.
  .replaceAll('float2', 'vec2').replaceAll('float3', 'vec3').replaceAll('float4', 'vec4')
  .replaceAll('half4', 'vec4').replaceAll('half3', 'vec3')
  // `half(x)` is a narrowing cast Metal wants and GLSL has no use for.
  .replace(/\bhalf\(([^()]*)\)/g, '$1')
  .replaceAll('atan2(', 'atan(')
  // GLSL ES will not compare a uint against an int literal.
  .replace(/(\buint \w+ = )(\d+)(; \w+ < )(\d+)(;)/g, '$1$2u$3$4u$5')
  // `float x = 0;` is an error in GLSL ES, and the Metal is written with bare integers.
  .replace(/(\bfloat \w+ = )([01]);/g, '$1$2.0;')

const body = translate(fragment)
  .replaceAll('input.uv', 'vUV')
  // Metal returns from a fragment; GLSL writes an out and returns nothing.
  .replace(/return vec4\(0\);/g, '{ outColor = vec4(0.0); return; }')
  .replace(/return vec4\(vec3\(color\), (\w+)\);/, 'outColor = vec4(color, $1);')
  // Anything still returning a value from main would be a translation the generator did not
  // anticipate, and a silently broken shader is worse than a failed build.
  .replace(/return\s+[^;]+;/g, match => { throw new Error(`Untranslated fragment return: ${match}`) })

const shader = `#version 300 es
precision highp float;
precision highp int;
struct MoonletPlanetUniforms {${translate(fields)}};
uniform MoonletPlanetUniforms u;
in vec2 vUV;
out vec4 outColor;
${translate(functions)}
void main() {${body}}
`

const vertex = `#version 300 es
precision highp float;
out vec2 vUV;
void main() {
  vec2 p = vec2(float(gl_VertexID & 1), float(gl_VertexID >> 1)) * 2.0 - 1.0;
  gl_Position = vec4(p, 0, 1);
  vUV = p * 0.5 + 0.5;
}
`

// A generated file that does not say so is a file somebody edits.
const output = `// Generated by \`npm run generate\` from Sources/MoonletPlanet/Shaders/PlanetRenderer.metal.
// Do not edit. Run \`npm run check:source\` to verify this is current.

export const fragmentShader = ${JSON.stringify(shader)}

export const vertexShader = ${JSON.stringify(vertex)}
`

const target = new URL('../src/shaders.ts', import.meta.url)
if (process.argv.includes('--check')) {
  let current = ''
  try { current = readFileSync(target, 'utf8') } catch { /* missing counts as stale */ }
  if (current !== output) {
    console.error('src/shaders.ts is out of date with PlanetRenderer.metal. Run `npm run generate`.')
    process.exit(1)
  }
  console.log('shader is in sync with the Metal source')
} else {
  writeFileSync(target, output)
  console.log('wrote src/shaders.ts')
}
