import Foundation
import MoonletPlanet

// Writes the web port's data from the Swift definitions, so the browser cannot disagree
// with the phone about what Jupiter is or about which planet a seed produces.
//
//     swift run PlanetExport
//
// Two files come out and neither is edited by hand:
//   web/src/presets.ts    every archetype and every named planet
//   web/tests/parity.json what `randomized(seed:)` produces here, for the port to match

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let encoder = JSONEncoder()
encoder.outputFormatting = [.prettyPrinted, .sortedKeys]

func json(_ recipe: MoonletPlanetRecipe) -> String {
    String(data: try! encoder.encode(recipe), encoding: .utf8)!
}

var lines = [
    "// Generated by `swift run PlanetExport`. Do not edit.",
    "//",
    "// These are the Swift package's own presets. A second hand-written copy is a copy that",
    "// disagrees with the phone about what Saturn looks like.",
    "",
    "import type { PlanetRecipe } from './index.ts'",
    ""
]

lines.append("export const archetypeRecipes = {")
for archetype in MoonletPlanetArchetype.allCases {
    lines.append("  \(archetype): \(json(.preset(archetype))) as PlanetRecipe,")
}
lines.append("} as const")
lines.append("")

lines.append("export const solarSystem = {")
for preset in MoonletPlanetPreset.allCases where preset != .custom {
    lines.append("  \(preset.rawValue): \(json(preset.style!.recipe)) as PlanetRecipe,")
}
lines.append("} as const")
lines.append("")
lines.append("/// Kept for the callers that had it before every preset was exported.")
lines.append("export const gasGiantRecipe: PlanetRecipe = archetypeRecipes.gasGiant")
lines.append("")

let presetsURL = root.appendingPathComponent("web/src/presets.ts")
try lines.joined(separator: "\n").write(to: presetsURL, atomically: true, encoding: .utf8)
print("wrote web/src/presets.ts")

// The randomizer is a seeded stream, so the port has to reproduce it exactly rather than
// merely plausibly. These are the numbers it has to hit.
struct ParityCase: Encodable {
    let seed: UInt32
    let archetype: UInt32
    let recipe: MoonletPlanetRecipe
}
let seeds: [UInt32] = [1, 7, 42, 240513, 4242, 65535, 999_999, 4_294_967_295]
var cases: [ParityCase] = []
for seed in seeds {
    for archetype in [MoonletPlanetArchetype.gasGiant, .ocean, .rocky] {
        let recipe = MoonletPlanetRecipe.preset(archetype).randomized(seed: seed)
        cases.append(ParityCase(seed: seed, archetype: archetype.rawValue, recipe: recipe))
    }
}
let parityURL = root.appendingPathComponent("web/tests/parity.json")
try FileManager.default.createDirectory(at: parityURL.deletingLastPathComponent(), withIntermediateDirectories: true)
try encoder.encode(cases).write(to: parityURL)
print("wrote web/tests/parity.json (\(cases.count) cases)")
