// Generated by `swift run PlanetExport`. Do not edit.
//
// These are the Swift package's own presets. A second hand-written copy is a copy that
// disagrees with the phone about what Saturn looks like.

import type { PlanetRecipe } from './index.ts'

export const archetypeRecipes = {
  gasGiant: {
  "archetype" : 0,
  "atmosphereDensity" : 0.52,
  "atmosphereGlow" : 0.62,
  "axialTilt" : 0,
  "bandCount" : 13,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.92,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.7,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.95,
      "green" : 0.72,
      "opacity" : 1,
      "red" : 0.48
    },
    "highlight" : {
      "blue" : 0.66,
      "green" : 0.86,
      "opacity" : 1,
      "red" : 0.96
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.16,
      "green" : 0.34,
      "opacity" : 1,
      "red" : 0.62
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.09,
      "green" : 0.07,
      "opacity" : 1,
      "red" : 0.12
    },
    "storm" : {
      "blue" : 0.36,
      "green" : 0.68,
      "opacity" : 1,
      "red" : 0.94
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.72,
  "seed" : 240513,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 5,
  "stormStrength" : 0.86,
  "turbulence" : 0.78,
  "warpStrength" : 0.76
} as PlanetRecipe,
  iceGiant: {
  "archetype" : 1,
  "atmosphereDensity" : 0.52,
  "atmosphereGlow" : 0.86,
  "axialTilt" : 0,
  "bandCount" : 8,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.92,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.7,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 1,
      "green" : 0.72,
      "opacity" : 1,
      "red" : 0.22
    },
    "highlight" : {
      "blue" : 1,
      "green" : 0.94,
      "opacity" : 1,
      "red" : 0.78
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.76,
      "green" : 0.55,
      "opacity" : 1,
      "red" : 0.16
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.2,
      "green" : 0.08,
      "opacity" : 1,
      "red" : 0.025
    },
    "storm" : {
      "blue" : 0.98,
      "green" : 0.88,
      "opacity" : 1,
      "red" : 0.53
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.48,
  "seed" : 240513,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 3,
  "stormStrength" : 0.52,
  "turbulence" : 0.48,
  "warpStrength" : 0.42
} as PlanetRecipe,
  ocean: {
  "archetype" : 2,
  "atmosphereDensity" : 0.52,
  "atmosphereGlow" : 0.62,
  "axialTilt" : 0,
  "bandCount" : 6,
  "bandSharpness" : 0.28,
  "cloudCoverage" : 0.58,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.7,
  "exposure" : 1.08,
  "featureAmount" : 0.64,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 1,
      "green" : 0.68,
      "opacity" : 1,
      "red" : 0.24
    },
    "highlight" : {
      "blue" : 0.98,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.62
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.58,
      "green" : 0.28,
      "opacity" : 1,
      "red" : 0.025
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.13,
      "green" : 0.035,
      "opacity" : 1,
      "red" : 0.01
    },
    "storm" : {
      "blue" : 1,
      "green" : 0.98,
      "opacity" : 1,
      "red" : 0.95
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.22,
  "seed" : 240513,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 4,
  "stormStrength" : 0.86,
  "turbulence" : 0.57,
  "warpStrength" : 0.54
} as PlanetRecipe,
  frozen: {
  "archetype" : 3,
  "atmosphereDensity" : 0.52,
  "atmosphereGlow" : 0.86,
  "axialTilt" : 0,
  "bandCount" : 4,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.3,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.92,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 1,
      "green" : 0.82,
      "opacity" : 1,
      "red" : 0.46
    },
    "highlight" : {
      "blue" : 1,
      "green" : 0.98,
      "opacity" : 1,
      "red" : 0.94
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.83,
      "green" : 0.7,
      "opacity" : 1,
      "red" : 0.42
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.24,
      "green" : 0.12,
      "opacity" : 1,
      "red" : 0.05
    },
    "storm" : {
      "blue" : 1,
      "green" : 0.94,
      "opacity" : 1,
      "red" : 0.72
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.035,
  "roughness" : 0.9,
  "seed" : 240513,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 1,
  "stormStrength" : 0.52,
  "turbulence" : 0.36,
  "warpStrength" : 0.28
} as PlanetRecipe,
  rocky: {
  "archetype" : 4,
  "atmosphereDensity" : 0.16,
  "atmosphereGlow" : 0.2,
  "axialTilt" : 0,
  "bandCount" : 3,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.08,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.82,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.3,
      "green" : 0.42,
      "opacity" : 1,
      "red" : 0.58
    },
    "highlight" : {
      "blue" : 0.5,
      "green" : 0.66,
      "opacity" : 1,
      "red" : 0.79
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.18,
      "green" : 0.24,
      "opacity" : 1,
      "red" : 0.35
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.06,
      "green" : 0.055,
      "opacity" : 1,
      "red" : 0.075
    },
    "storm" : {
      "blue" : 0.28,
      "green" : 0.42,
      "opacity" : 1,
      "red" : 0.54
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.025,
  "roughness" : 0.96,
  "seed" : 240513,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 0,
  "stormStrength" : 0.86,
  "turbulence" : 0.7,
  "warpStrength" : 0.33
} as PlanetRecipe,
  molten: {
  "archetype" : 5,
  "atmosphereDensity" : 0.38,
  "atmosphereGlow" : 0.74,
  "axialTilt" : 0,
  "bandCount" : 3,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.18,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.9,
  "exposure" : 1.18,
  "featureAmount" : 0.88,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.03,
      "green" : 0.19,
      "opacity" : 1,
      "red" : 1
    },
    "highlight" : {
      "blue" : 0.26,
      "green" : 0.86,
      "opacity" : 1,
      "red" : 1
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.025,
      "green" : 0.19,
      "opacity" : 1,
      "red" : 0.95
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.012,
      "green" : 0.008,
      "opacity" : 1,
      "red" : 0.035
    },
    "storm" : {
      "blue" : 0.04,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 1
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.045,
  "roughness" : 0.88,
  "seed" : 240513,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 0,
  "stormStrength" : 0.86,
  "turbulence" : 0.84,
  "warpStrength" : 0.58
} as PlanetRecipe,
  desert: {
  "archetype" : 6,
  "atmosphereDensity" : 0.26,
  "atmosphereGlow" : 0.2,
  "axialTilt" : 0,
  "bandCount" : 3,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.08,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.7,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.22,
      "green" : 0.52,
      "opacity" : 1,
      "red" : 0.96
    },
    "highlight" : {
      "blue" : 0.43,
      "green" : 0.78,
      "opacity" : 1,
      "red" : 0.98
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.12,
      "green" : 0.31,
      "opacity" : 1,
      "red" : 0.68
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.045,
      "green" : 0.07,
      "opacity" : 1,
      "red" : 0.16
    },
    "storm" : {
      "blue" : 0.26,
      "green" : 0.57,
      "opacity" : 1,
      "red" : 0.9
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.025,
  "roughness" : 0.96,
  "seed" : 240513,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 0,
  "stormStrength" : 0.86,
  "turbulence" : 0.58,
  "warpStrength" : 0.42
} as PlanetRecipe,
  toxic: {
  "archetype" : 7,
  "atmosphereDensity" : 0.78,
  "atmosphereGlow" : 0.92,
  "axialTilt" : 0,
  "bandCount" : 9,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.92,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.7,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.24,
      "green" : 1,
      "opacity" : 1,
      "red" : 0.46
    },
    "highlight" : {
      "blue" : 0.36,
      "green" : 1,
      "opacity" : 1,
      "red" : 0.83
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.14,
      "green" : 0.58,
      "opacity" : 1,
      "red" : 0.2
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.055,
      "green" : 0.12,
      "opacity" : 1,
      "red" : 0.025
    },
    "storm" : {
      "blue" : 0.16,
      "green" : 0.78,
      "opacity" : 1,
      "red" : 0.92
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.72,
  "seed" : 240513,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 4,
  "stormStrength" : 0.86,
  "turbulence" : 0.78,
  "warpStrength" : 0.76
} as PlanetRecipe,
  lush: {
  "archetype" : 8,
  "atmosphereDensity" : 0.52,
  "atmosphereGlow" : 0.62,
  "axialTilt" : 0,
  "bandCount" : 6,
  "bandSharpness" : 0.28,
  "cloudCoverage" : 0.42,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.7,
  "exposure" : 1.08,
  "featureAmount" : 0.84,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.72,
      "green" : 0.88,
      "opacity" : 1,
      "red" : 0.24
    },
    "highlight" : {
      "blue" : 0.84,
      "green" : 0.96,
      "opacity" : 1,
      "red" : 0.75
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.34,
      "green" : 0.29,
      "opacity" : 1,
      "red" : 0.025
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.075,
      "green" : 0.055,
      "opacity" : 1,
      "red" : 0.012
    },
    "storm" : {
      "blue" : 0.25,
      "green" : 0.62,
      "opacity" : 1,
      "red" : 0.12
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.22,
  "seed" : 240513,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 4,
  "stormStrength" : 0.86,
  "turbulence" : 0.57,
  "warpStrength" : 0.54
} as PlanetRecipe,
  cloud: {
  "archetype" : 9,
  "atmosphereDensity" : 0.86,
  "atmosphereGlow" : 0.62,
  "axialTilt" : 0,
  "bandCount" : 13,
  "bandSharpness" : 0.22,
  "cloudCoverage" : 1,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.7,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.68,
      "green" : 0.76,
      "opacity" : 1,
      "red" : 0.9
    },
    "highlight" : {
      "blue" : 0.86,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 1
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.55,
      "green" : 0.68,
      "opacity" : 1,
      "red" : 0.82
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.18,
      "green" : 0.14,
      "opacity" : 1,
      "red" : 0.22
    },
    "storm" : {
      "blue" : 0.66,
      "green" : 0.82,
      "opacity" : 1,
      "red" : 0.98
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.72,
  "seed" : 240513,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 5,
  "stormStrength" : 0.86,
  "turbulence" : 0.44,
  "warpStrength" : 0.76
} as PlanetRecipe,
} as const

export const solarSystem = {
  earth: {
  "archetype" : 2,
  "atmosphereDensity" : 0.52,
  "atmosphereGlow" : 0.62,
  "axialTilt" : 0.409,
  "bandCount" : 6,
  "bandSharpness" : 0.28,
  "cloudCoverage" : 0.54,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.7,
  "exposure" : 1.08,
  "featureAmount" : 0.72,
  "iceAltitude" : 0.34,
  "iceCoverage" : 0.19,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 1,
      "green" : 0.62,
      "opacity" : 1,
      "red" : 0.22
    },
    "highlight" : {
      "blue" : 1,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.86
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.56,
      "green" : 0.22,
      "opacity" : 1,
      "red" : 0.02
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.11,
      "green" : 0.025,
      "opacity" : 1,
      "red" : 0.005
    },
    "storm" : {
      "blue" : 0.18,
      "green" : 0.48,
      "opacity" : 1,
      "red" : 0.08
    }
  },
  "polarAsymmetry" : 0.16,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.22,
  "seed" : 39916801,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 4,
  "stormStrength" : 0.86,
  "turbulence" : 0.57,
  "warpStrength" : 0.54
} as PlanetRecipe,
  mars: {
  "archetype" : 6,
  "atmosphereDensity" : 0.11,
  "atmosphereGlow" : 0.2,
  "axialTilt" : 0.44,
  "bandCount" : 3,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.08,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.7,
  "iceAltitude" : 0.18,
  "iceCoverage" : 0.15,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.22,
      "green" : 0.52,
      "opacity" : 1,
      "red" : 0.96
    },
    "highlight" : {
      "blue" : 0.43,
      "green" : 0.78,
      "opacity" : 1,
      "red" : 0.98
    },
    "ice" : {
      "blue" : 0.94,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.96
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.07,
      "green" : 0.18,
      "opacity" : 1,
      "red" : 0.62
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.025,
      "green" : 0.035,
      "opacity" : 1,
      "red" : 0.12
    },
    "storm" : {
      "blue" : 0.26,
      "green" : 0.57,
      "opacity" : 1,
      "red" : 0.9
    }
  },
  "polarAsymmetry" : 0.34,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.025,
  "roughness" : 0.96,
  "seed" : 14479891,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 0,
  "stormStrength" : 0.86,
  "turbulence" : 0.58,
  "warpStrength" : 0.42
} as PlanetRecipe,
  jupiter: {
  "archetype" : 0,
  "atmosphereDensity" : 0.52,
  "atmosphereGlow" : 0.62,
  "axialTilt" : 0,
  "bandCount" : 13,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.92,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.7,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.95,
      "green" : 0.72,
      "opacity" : 1,
      "red" : 0.48
    },
    "highlight" : {
      "blue" : 0.66,
      "green" : 0.86,
      "opacity" : 1,
      "red" : 0.96
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.16,
      "green" : 0.34,
      "opacity" : 1,
      "red" : 0.62
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.09,
      "green" : 0.07,
      "opacity" : 1,
      "red" : 0.12
    },
    "storm" : {
      "blue" : 0.36,
      "green" : 0.68,
      "opacity" : 1,
      "red" : 0.94
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.72,
  "seed" : 125573,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 5,
  "stormStrength" : 0.86,
  "turbulence" : 0.78,
  "warpStrength" : 0.76
} as PlanetRecipe,
  saturn: {
  "archetype" : 0,
  "atmosphereDensity" : 0.52,
  "atmosphereGlow" : 0.62,
  "axialTilt" : 0.47,
  "bandCount" : 18,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.92,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.7,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.55,
      "green" : 0.72,
      "opacity" : 1,
      "red" : 0.82
    },
    "highlight" : {
      "blue" : 0.7,
      "green" : 0.91,
      "opacity" : 1,
      "red" : 1
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.36,
      "green" : 0.58,
      "opacity" : 1,
      "red" : 0.76
    },
    "ring" : {
      "blue" : 0.78,
      "green" : 0.88,
      "opacity" : 1,
      "red" : 0.93
    },
    "shadow" : {
      "blue" : 0.11,
      "green" : 0.14,
      "opacity" : 1,
      "red" : 0.21
    },
    "storm" : {
      "blue" : 0.54,
      "green" : 0.76,
      "opacity" : 1,
      "red" : 0.9
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.9,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 1,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.72,
  "seed" : 138759,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 1,
  "stormStrength" : 0.86,
  "turbulence" : 0.34,
  "warpStrength" : 0.76
} as PlanetRecipe,
  uranus: {
  "archetype" : 1,
  "atmosphereDensity" : 0.52,
  "atmosphereGlow" : 0.86,
  "axialTilt" : 1.32,
  "bandCount" : 5,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.92,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.7,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 1,
      "green" : 0.72,
      "opacity" : 1,
      "red" : 0.22
    },
    "highlight" : {
      "blue" : 1,
      "green" : 0.94,
      "opacity" : 1,
      "red" : 0.78
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.74,
      "green" : 0.72,
      "opacity" : 1,
      "red" : 0.3
    },
    "ring" : {
      "blue" : 0.66,
      "green" : 0.62,
      "opacity" : 1,
      "red" : 0.58
    },
    "shadow" : {
      "blue" : 0.24,
      "green" : 0.18,
      "opacity" : 1,
      "red" : 0.04
    },
    "storm" : {
      "blue" : 0.98,
      "green" : 0.88,
      "opacity" : 1,
      "red" : 0.53
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.5,
  "ringInnerRadius" : 1.64,
  "ringOpacity" : 1,
  "ringOuterRadius" : 2,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.48,
  "seed" : 948291,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 1,
  "stormStrength" : 0.52,
  "turbulence" : 0.48,
  "warpStrength" : 0.42
} as PlanetRecipe,
  neptune: {
  "archetype" : 1,
  "atmosphereDensity" : 0.52,
  "atmosphereGlow" : 0.86,
  "axialTilt" : 0.49,
  "bandCount" : 8,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.92,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.7,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 1,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.16
    },
    "highlight" : {
      "blue" : 1,
      "green" : 0.94,
      "opacity" : 1,
      "red" : 0.78
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.72,
      "green" : 0.23,
      "opacity" : 1,
      "red" : 0.055
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.18,
      "green" : 0.025,
      "opacity" : 1,
      "red" : 0.01
    },
    "storm" : {
      "blue" : 0.98,
      "green" : 0.88,
      "opacity" : 1,
      "red" : 0.53
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.48,
  "seed" : 614271,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 4,
  "stormStrength" : 0.8,
  "turbulence" : 0.48,
  "warpStrength" : 0.42
} as PlanetRecipe,
  venus: {
  "archetype" : 9,
  "atmosphereDensity" : 0.96,
  "atmosphereGlow" : 0.62,
  "axialTilt" : 0,
  "bandCount" : 13,
  "bandSharpness" : 0.22,
  "cloudCoverage" : 1,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.7,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.68,
      "green" : 0.76,
      "opacity" : 1,
      "red" : 0.9
    },
    "highlight" : {
      "blue" : 0.86,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 1
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.22,
      "green" : 0.53,
      "opacity" : 1,
      "red" : 0.78
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.055,
      "green" : 0.12,
      "opacity" : 1,
      "red" : 0.22
    },
    "storm" : {
      "blue" : 0.66,
      "green" : 0.82,
      "opacity" : 1,
      "red" : 0.98
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.11,
  "roughness" : 0.72,
  "seed" : 871923,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 5,
  "stormStrength" : 0.86,
  "turbulence" : 0.44,
  "warpStrength" : 0.76
} as PlanetRecipe,
  mercury: {
  "archetype" : 4,
  "atmosphereDensity" : 0,
  "atmosphereGlow" : 0,
  "axialTilt" : 0,
  "bandCount" : 3,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.08,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.82,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.3,
      "green" : 0.42,
      "opacity" : 1,
      "red" : 0.58
    },
    "highlight" : {
      "blue" : 0.64,
      "green" : 0.71,
      "opacity" : 1,
      "red" : 0.76
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.34,
      "green" : 0.38,
      "opacity" : 1,
      "red" : 0.42
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.06,
      "green" : 0.055,
      "opacity" : 1,
      "red" : 0.075
    },
    "storm" : {
      "blue" : 0.28,
      "green" : 0.42,
      "opacity" : 1,
      "red" : 0.54
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.025,
  "roughness" : 0.96,
  "seed" : 128667,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 0,
  "stormStrength" : 0.86,
  "turbulence" : 0.7,
  "warpStrength" : 0.33
} as PlanetRecipe,
  moon: {
  "archetype" : 4,
  "atmosphereDensity" : 0,
  "atmosphereGlow" : 0,
  "axialTilt" : 0,
  "bandCount" : 3,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.08,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.82,
  "iceAltitude" : 0.22,
  "iceCoverage" : 0,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 0.3,
      "green" : 0.42,
      "opacity" : 1,
      "red" : 0.58
    },
    "highlight" : {
      "blue" : 0.78,
      "green" : 0.82,
      "opacity" : 1,
      "red" : 0.83
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.47,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.46
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.095,
      "green" : 0.08,
      "opacity" : 1,
      "red" : 0.08
    },
    "storm" : {
      "blue" : 0.28,
      "green" : 0.42,
      "opacity" : 1,
      "red" : 0.54
    }
  },
  "polarAsymmetry" : 0,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.025,
  "roughness" : 0.96,
  "seed" : 240513,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 0,
  "stormStrength" : 0.86,
  "turbulence" : 0.7,
  "warpStrength" : 0.33
} as PlanetRecipe,
  pluto: {
  "archetype" : 3,
  "atmosphereDensity" : 0.03,
  "atmosphereGlow" : 0.86,
  "axialTilt" : 0,
  "bandCount" : 4,
  "bandSharpness" : 0.62,
  "cloudCoverage" : 0.3,
  "cloudSpeed" : 0.65,
  "dayNightSpeed" : 0,
  "detail" : 0.82,
  "exposure" : 1.08,
  "featureAmount" : 0.92,
  "iceAltitude" : 0.12,
  "iceCoverage" : 0.55,
  "life" : 0,
  "lightAzimuth" : 2.2,
  "lightElevation" : 0.46,
  "microDetail" : 1,
  "palette" : {
    "atmosphere" : {
      "blue" : 1,
      "green" : 0.82,
      "opacity" : 1,
      "red" : 0.46
    },
    "highlight" : {
      "blue" : 0.67,
      "green" : 0.76,
      "opacity" : 1,
      "red" : 0.88
    },
    "ice" : {
      "blue" : 0.97,
      "green" : 0.95,
      "opacity" : 1,
      "red" : 0.93
    },
    "life" : {
      "blue" : 0.2,
      "green" : 0.46,
      "opacity" : 1,
      "red" : 0.28
    },
    "primary" : {
      "blue" : 0.38,
      "green" : 0.45,
      "opacity" : 1,
      "red" : 0.58
    },
    "ring" : {
      "blue" : 0.83,
      "green" : 0.9,
      "opacity" : 1,
      "red" : 0.94
    },
    "shadow" : {
      "blue" : 0.24,
      "green" : 0.12,
      "opacity" : 1,
      "red" : 0.05
    },
    "storm" : {
      "blue" : 1,
      "green" : 0.94,
      "opacity" : 1,
      "red" : 0.72
    }
  },
  "polarAsymmetry" : -0.24,
  "ringDetail" : 0.8,
  "ringInnerRadius" : 1.235,
  "ringOpacity" : 0,
  "ringOuterRadius" : 2.27,
  "rotationPhase" : 0,
  "rotationSpeed" : 0.035,
  "roughness" : 0.9,
  "seed" : 551902,
  "stationCount" : 1,
  "stationInclination" : 0.9,
  "stationOrbitRadius" : 1.085,
  "stationSize" : 1,
  "stationSpeed" : 0.55,
  "stormCount" : 1,
  "stormStrength" : 0.52,
  "turbulence" : 0.36,
  "warpStrength" : 0.28
} as PlanetRecipe,
} as const

/// Kept for the callers that had it before every preset was exported.
export const gasGiantRecipe: PlanetRecipe = archetypeRecipes.gasGiant
