// The seeded palette generator, ported from Swift so the same seed is the same planet in
// both places.
//
// This is SplitMix64 and it is reproduced exactly rather than approximately — `randomized`
// promises that a seed is a planet somebody can come back to, and a port that merely looks
// random breaks that promise silently. `tests/parity.json` is generated by the Swift package
// and is what holds the two together.

import type { PlanetColor, PlanetRecipe } from './index.ts'

const MASK = (1n << 64n) - 1n
const GOLDEN = 0x9e3779b97f4a7c15n

class SplitMix64 {
  private state: bigint
  constructor(seed: number) { this.state = BigInt(seed >>> 0) }

  next(): number {
    this.state = (this.state + GOLDEN) & MASK
    let value = this.state
    value = ((value ^ (value >> 30n)) * 0xbf58476d1ce4e5b9n) & MASK
    value = ((value ^ (value >> 27n)) * 0x94d049bb133111ebn) & MASK
    value ^= value >> 31n
    // Swift takes the top 53 bits and divides by 2^53, which is exactly a double's mantissa.
    return Number(value >> 11n) / 9007199254740992
  }

  in(lower: number, upper: number): number {
    return lower + this.next() * (upper - lower)
  }
}

/** HSB to RGB, matching `MoonletColor(hue:saturation:brightness:)`. Hue wraps rather than clamps. */
export function colorFromHSB(hue: number, saturation: number, brightness: number, opacity = 1): PlanetColor {
  const normalized = ((hue % 1) + 1) % 1
  const sector = normalized * 6
  const index = Math.floor(sector)
  const fraction = sector - index
  const p = brightness * (1 - saturation)
  const q = brightness * (1 - saturation * fraction)
  const t = brightness * (1 - saturation * (1 - fraction))
  const rgb: [number, number, number] = [
    [brightness, t, p], [q, brightness, p], [p, brightness, t],
    [p, q, brightness], [t, p, brightness], [brightness, p, q],
  ][index % 6] as [number, number, number]
  return { red: rgb[0], green: rgb[1], blue: rgb[2], opacity }
}

/**
 * A new palette from a seed, leaving every other field alone.
 *
 * Same order of draws as the Swift, because the order *is* the algorithm: moving one call
 * shifts every number after it and produces a different planet for the same seed.
 */
export function randomized(recipe: PlanetRecipe, seed: number): PlanetRecipe {
  const g = new SplitMix64(seed)
  const baseHue = g.next()
  const accentHue = (baseHue + g.in(0.08, 0.24)) % 1
  const palette = {
    highlight: colorFromHSB(accentHue, g.in(0.28, 0.62), g.in(0.88, 1)),
    primary: colorFromHSB(baseHue, g.in(0.54, 0.92), g.in(0.46, 0.78)),
    shadow: colorFromHSB((baseHue + g.in(0, 0.08)) % 1, g.in(0.48, 0.9), g.in(0.06, 0.2)),
    storm: colorFromHSB(accentHue, g.in(0.52, 0.94), g.in(0.72, 1)),
    atmosphere: colorFromHSB((baseHue + g.in(0.12, 0.34)) % 1, g.in(0.48, 0.88), g.in(0.74, 1)),
    ring: recipe.palette.ring,
    ice: recipe.palette.ice,
  }
  return { ...recipe, seed: seed >>> 0, palette }
}
